DELETE FROM [dbo].[effects];
INSERT INTO [dbo].[effects] ([id], [desc]) VALUES
(1, 'invoque le climat'),
(2, 'brûlure'),
(3, 'appeurer'),
(4, 'priorité'),
(5, 'piège'),
(6, 'recul'),
(7, 'modif atk'),
(8, 'modif def'),
(9, 'modif spa'),
(10, 'modif spd'),
(11, 'modif spe'),
(12, 'inflige dégâts par tour'),
(13, 'soigne'),
(14, 'endors'),
(15, 'soigne des dégâts infligés'),
(16, 'crit'),
(17, 'inflige'),
(18, 'soigne dégâts par tour'),
(19, 'frappe 2 à 5 fois'),
(20, 'protege'),
(21, 'paralyse'),
(22, 'pivot'),
(23, 'recharge'),
(24, 'substitute'),
(25, 'passe à travers substitute'),
(26, 'retire les hazards'),
(27, 'si miss perd'),
(28, 'modif atk adv'),
(29, 'modif def adv'),
(30, 'modif spa adv'),
(31, 'modif spd adv'),
(32, 'modif spe adv'),
(33, 'confus'),
(34, 'bloque n tours'),
(35, 'degats en fonction de la def adv'),
(36, 'gêle'),
(37, 'prec 100 si météo'),
(38, 'piege de roc'),
(39, 'picots'),
(40, 'sabotage'),
(41, 'empoisonne'),
(42, 'empoisonne gravement'),
(43, 'acrobatie'),
(44, 'pics toxic'),
(45, 'provoc'),
(46, 'echange les objets'),
(47, 'protection'),
(48, 'mur lumière'),
(49, 'voeu soin'),
(50, 'toile gluante'),
(51, 'atterit'),
(52, 'reset toutes les stats');
