DELETE FROM [dbo].[talents];
INSERT INTO [dbo].[talents] ([id], [nom]) VALUES
(1, 'Static'),
(2, 'Lightning rod'),
(3, 'Blaze'),
(4, 'Overgrow'),
(5, 'Torrent'),
(6, 'Solar power'),
(7, 'Chlorophyll'),
(8, 'Rain dish'),
(9, 'Inner focus'),
(10, 'Magic guard'),
(11, 'Natural cure'),
(12, 'Unaware'),
(13, 'Cursed body'),
(14, 'Pressure'),
(15, 'Leaf guard'),
(16, 'Flash fire'),
(17, 'Sheer force'),
(18, 'Infiltrator'),
(19, 'Sap sipper'),
(20, 'Huge power'),
(21, 'Swarm'),
(22, 'Technician'),
(23, 'Sturdy'),
(24, 'Weak armor'),
(25, 'Sand stream'),
(26, 'Unburden'),
(27, 'Speed boost'),
(28, 'Damp'),
(29, 'Synchronize'),
(30, 'Trace'),
(31, 'Poison heal'),
(32, 'Keen eye'),
(33, 'Prankster'),
(34, 'Intimidate'),
(35, 'Clear body'),
(36, 'Levitate'),
(37, 'Shell armor'),
(38, 'Iron fist'),
(39, 'Defiant'),
(40, 'Reckless'),
(41, 'Steadfast'),
(42, 'Justified'),
(43, 'Magnet pull'),
(44, 'Serene grace'),
(45, 'Super luck'),
(46, 'Oblivious'),
(47, 'Thick fat'),
(48, 'Contrary'),
(49, 'Victory star'),
(50, 'Sand rush'),
(51, 'Mold breaker'),
(52, 'Flame body'),
(53, 'Iron barbs'),
(54, 'Bulletproof'),
(55, 'Magician'),
(56, 'Protean'),
(57, 'Battle bond'),
(58, 'Gooey'),
(59, 'Pixilate'),
(60, 'Cute charm'),
(61, 'Gale wings'),
(62, 'Pickup'),
(63, 'Aura break'),
(64, 'Long reach'),
(65, 'Liquid voice'),
(66, 'Merciless'),
(67, 'Regenerator'),
(68, 'Overcoat'),
(69, 'Electric surge'),
(70, 'Psychic surge'),
(71, 'Beast boost'),
(72, 'Soul-heart');
